export const bgColors = {
    normal: 'bg-normal',
    fire: 'bg-fire',
    water: 'bg-water',
    electric: 'bg-electric',
    grass: 'bg-grass',
    ice: 'bg-ice',
    fighting: 'bg-fighting',
    poison: 'bg-poison',
    ground: 'bg-ground',
    flying: 'bg-flying',
    psychic: 'bg-psychic',
    bug: 'bg-bug',
    rock: 'bg-rock',
    ghost: 'bg-ghost',
    dragon: 'bg-dragon',
    dark: 'bg-dark',
    steel: 'bg-steel',
    fairy: 'bg-fairy',
};

export const borderColors = {
    normal: 'border-normal-darker',
    fire: 'border-fire-darker',
    water: 'border-water-darker',
    electric: 'border-electric-darker',
    grass: 'border-grass-darker',
    ice: 'border-ice-darker',
    fighting: 'border-fighting-darker',
    poison: 'border-poison-darker',
    ground: 'border-ground-darker',
    flying: 'border-flying-darker',
    psychic: 'border-psychic-darker',
    bug: 'border-bug-darker',
    rock: 'border-rock-darker',
    ghost: 'border-ghost-darker',
    dragon: 'border-dragon-darker',
    dark: 'border-dark-darker',
    steel: 'border-steel-darker',
    fairy: 'border-fairy-darker',
};

export const badgeColors = {
    normal: 'badge-normal',
    fire: 'badge-fire',
    water: 'badge-water',
    electric: 'badge-electric',
    grass: 'badge-grass',
    ice: 'badge-ice',
    fighting: 'badge-fighting',
    poison: 'badge-poison',
    ground: 'badge-ground',
    flying: 'badge-flying',
    psychic: 'badge-psychic',
    bug: 'badge-bug',
    rock: 'badge-rock',
    ghost: 'badge-ghost',
    dragon: 'badge-dragon',
    dark: 'badge-dark',
    steel: 'badge-steel',
    fairy: 'badge-fairy',
};
